version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY-}mangatiappserver
    build:
      context: .
      dockerfile: Mangati.App/Mangati.App.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=MangatiApp;User Id=sa;Password=${DB_PASSWORD:-YourStr0ngP@ssw0rd};TrustServerCertificate=True
    depends_on:
      - db
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Mangati.App/mangati.app.client/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/azure-sql-edge:latest  # Lightweight SQL Server for containers
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=${DB_PASSWORD:-YourStr0ngP@ssw0rd}
    ports:
      - "1433:1433"
    volumes:
      - mangati-db:/var/opt/mssql
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G
        reservations:
          cpus: '0.35'
          memory: 512M
    restart: unless-stopped

volumes:
  mangati-db: